name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mask-aws-account-id: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=v0.69.13
          wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3

      - name: Initialize TFLint
        working-directory: tf
        run: tflint --init
        
      - name: Run TFLint
        working-directory: tf
        run: tflint -f compact --recursive

      - name: Terragrunt Format Check
        working-directory: tf/environments/prod
        run: terragrunt hclfmt --terragrunt-check

      - name: Terragrunt Validate
        working-directory: tf/environments/prod
        run: terragrunt validate

      - name: Terragrunt Plan
        working-directory: tf/environments/prod
        run: terragrunt plan -out=tfplan
      
      # - name: Terragrunt Apply
      #   working-directory: tf/environments/prod
      #   run: terragrunt apply tfplan

      # - name: Deploy to S3
      #   working-directory: tf/environments/prod
      #   run: |
      #     aws s3 sync ../../frontend/dist/ s3://$(terragrunt output -raw website_bucket_name)
      #     aws cloudfront create-invalidation --distribution-id $(terragrunt output -raw cloudfront_distribution_id) --paths "/*"
